[images]
  remote_images = ["https://ext.same-assets.com/*"]

[build]
  command = "cd sesame-clone && bun run build"
  publish = "sesame-clone/.next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
